services:
  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: athena-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --maxmemory 2gb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - athena-network

  # API Server
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: athena-api
    ports:
      - "3000:3000"
      - "9090:9090"  # Metrics port
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WASM_MEMORY_LIMIT=512
      - WASM_ENABLE_BULK_MEMORY=true
      - LOG_LEVEL=info
      - METRICS_ENABLED=true
      - METRICS_PORT=9090
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - wasm-cache:/app/wasm-cache
    networks:
      - athena-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Prometheus for metrics (required for WASM monitoring)
  prometheus:
    build:
      context: .
      dockerfile: Dockerfile.prometheus
    container_name: athena-prometheus
    ports:
      - "9091:9090"
    volumes:
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - athena-network
    depends_on:
      - api

  # Grafana for WASM performance dashboards
  grafana:
    image: grafana/grafana:latest
    container_name: athena-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - athena-network
    depends_on:
      - prometheus

networks:
  athena-network:
    driver: bridge

volumes:
  redis-data:
  wasm-cache:
  prometheus-data:
  grafana-data: