apiVersion: v1
kind: Secret
metadata:
  name: athena-ai-secrets
  namespace: athena
type: Opaque
stringData:
  CLAUDE_API_KEY: "YOUR_CLAUDE_API_KEY_HERE"
  DEEPSEEK_API_KEY: "YOUR_DEEPSEEK_API_KEY_HERE"
  OPENAI_API_KEY: "YOUR_OPENAI_API_KEY_HERE"
---
apiVersion: v1
kind: Secret
metadata:
  name: athena-redis-secret
  namespace: athena
type: Opaque
stringData:
  REDIS_PASSWORD: "YOUR_STRONG_REDIS_PASSWORD_HERE"
---
apiVersion: v1
kind: Secret
metadata:
  name: athena-app-secrets
  namespace: athena
type: Opaque
stringData:
  JWT_SECRET: "YOUR_JWT_SECRET_HERE"
  SESSION_SECRET: "YOUR_SESSION_SECRET_HERE"
  ENCRYPTION_KEY: "YOUR_ENCRYPTION_KEY_HERE"