// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod athena {
        pub mod sandbox {
            /// Secure sandbox execution for malware analysis
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod sandbox {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                /// Resource usage tracking
                #[repr(C)]
                #[derive(Clone, Copy)]
                pub struct ResourceUsage {
                    pub memory_bytes: u64,
                    pub cpu_time_ms: u64,
                    pub syscalls_count: u32,
                }
                impl ::core::fmt::Debug for ResourceUsage {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("ResourceUsage")
                            .field("memory-bytes", &self.memory_bytes)
                            .field("cpu-time-ms", &self.cpu_time_ms)
                            .field("syscalls-count", &self.syscalls_count)
                            .finish()
                    }
                }
                /// Security event type
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum SecurityEventType {
                    SyscallBlocked,
                    MemoryLimitReached,
                    CpuLimitReached,
                    NetworkAccessAttempt,
                    FileAccessAttempt,
                    SuspiciousBehavior,
                }
                impl ::core::fmt::Debug for SecurityEventType {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            SecurityEventType::SyscallBlocked => {
                                f.debug_tuple("SecurityEventType::SyscallBlocked").finish()
                            }
                            SecurityEventType::MemoryLimitReached => {
                                f.debug_tuple("SecurityEventType::MemoryLimitReached")
                                    .finish()
                            }
                            SecurityEventType::CpuLimitReached => {
                                f.debug_tuple("SecurityEventType::CpuLimitReached").finish()
                            }
                            SecurityEventType::NetworkAccessAttempt => {
                                f.debug_tuple("SecurityEventType::NetworkAccessAttempt")
                                    .finish()
                            }
                            SecurityEventType::FileAccessAttempt => {
                                f.debug_tuple("SecurityEventType::FileAccessAttempt")
                                    .finish()
                            }
                            SecurityEventType::SuspiciousBehavior => {
                                f.debug_tuple("SecurityEventType::SuspiciousBehavior")
                                    .finish()
                            }
                        }
                    }
                }
                impl SecurityEventType {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> SecurityEventType {
                        if !cfg!(debug_assertions) {
                            return ::core::mem::transmute(val);
                        }
                        match val {
                            0 => SecurityEventType::SyscallBlocked,
                            1 => SecurityEventType::MemoryLimitReached,
                            2 => SecurityEventType::CpuLimitReached,
                            3 => SecurityEventType::NetworkAccessAttempt,
                            4 => SecurityEventType::FileAccessAttempt,
                            5 => SecurityEventType::SuspiciousBehavior,
                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }
                /// Security severity
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum SecuritySeverity {
                    Low,
                    Medium,
                    High,
                    Critical,
                }
                impl ::core::fmt::Debug for SecuritySeverity {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            SecuritySeverity::Low => {
                                f.debug_tuple("SecuritySeverity::Low").finish()
                            }
                            SecuritySeverity::Medium => {
                                f.debug_tuple("SecuritySeverity::Medium").finish()
                            }
                            SecuritySeverity::High => {
                                f.debug_tuple("SecuritySeverity::High").finish()
                            }
                            SecuritySeverity::Critical => {
                                f.debug_tuple("SecuritySeverity::Critical").finish()
                            }
                        }
                    }
                }
                impl SecuritySeverity {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> SecuritySeverity {
                        if !cfg!(debug_assertions) {
                            return ::core::mem::transmute(val);
                        }
                        match val {
                            0 => SecuritySeverity::Low,
                            1 => SecuritySeverity::Medium,
                            2 => SecuritySeverity::High,
                            3 => SecuritySeverity::Critical,
                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }
                /// Security event
                #[derive(Clone)]
                pub struct SecurityEvent {
                    pub timestamp: u64,
                    pub event_type: SecurityEventType,
                    pub description: _rt::String,
                    pub severity: SecuritySeverity,
                }
                impl ::core::fmt::Debug for SecurityEvent {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("SecurityEvent")
                            .field("timestamp", &self.timestamp)
                            .field("event-type", &self.event_type)
                            .field("description", &self.description)
                            .field("severity", &self.severity)
                            .finish()
                    }
                }
                /// Execution policy
                #[derive(Clone)]
                pub struct ExecutionPolicy {
                    pub max_memory_bytes: u64,
                    pub max_cpu_time_ms: u64,
                    pub max_execution_time_ms: u64,
                    pub allow_network: bool,
                    pub allow_file_access: bool,
                    pub allowed_syscalls: _rt::Vec<_rt::String>,
                }
                impl ::core::fmt::Debug for ExecutionPolicy {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("ExecutionPolicy")
                            .field("max-memory-bytes", &self.max_memory_bytes)
                            .field("max-cpu-time-ms", &self.max_cpu_time_ms)
                            .field("max-execution-time-ms", &self.max_execution_time_ms)
                            .field("allow-network", &self.allow_network)
                            .field("allow-file-access", &self.allow_file_access)
                            .field("allowed-syscalls", &self.allowed_syscalls)
                            .finish()
                    }
                }
                /// Execution result
                #[derive(Clone)]
                pub struct ExecutionResult {
                    pub stdout: _rt::String,
                    pub stderr: _rt::String,
                    pub exit_code: i32,
                    pub resource_usage: ResourceUsage,
                    pub security_events: _rt::Vec<SecurityEvent>,
                    pub execution_time_ms: u64,
                    pub success: bool,
                }
                impl ::core::fmt::Debug for ExecutionResult {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("ExecutionResult")
                            .field("stdout", &self.stdout)
                            .field("stderr", &self.stderr)
                            .field("exit-code", &self.exit_code)
                            .field("resource-usage", &self.resource_usage)
                            .field("security-events", &self.security_events)
                            .field("execution-time-ms", &self.execution_time_ms)
                            .field("success", &self.success)
                            .finish()
                    }
                }
                /// Resource handle for sandbox manager
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct SandboxManager {
                    handle: _rt::Resource<SandboxManager>,
                }
                type _SandboxManagerRep<T> = Option<T>;
                impl SandboxManager {
                    /// Creates a new resource from the specified representation.
                    ///
                    /// This function will create a new resource handle by moving `val` onto
                    /// the heap and then passing that heap pointer to the component model to
                    /// create a handle. The owned handle is then returned as `SandboxManager`.
                    pub fn new<T: GuestSandboxManager>(val: T) -> Self {
                        Self::type_guard::<T>();
                        let val: _SandboxManagerRep<T> = Some(val);
                        let ptr: *mut _SandboxManagerRep<T> = _rt::Box::into_raw(
                            _rt::Box::new(val),
                        );
                        unsafe { Self::from_handle(T::_resource_new(ptr.cast())) }
                    }
                    /// Gets access to the underlying `T` which represents this resource.
                    pub fn get<T: GuestSandboxManager>(&self) -> &T {
                        let ptr = unsafe { &*self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }
                    /// Gets mutable access to the underlying `T` which represents this
                    /// resource.
                    pub fn get_mut<T: GuestSandboxManager>(&mut self) -> &mut T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_mut().unwrap()
                    }
                    /// Consumes this resource and returns the underlying `T`.
                    pub fn into_inner<T: GuestSandboxManager>(self) -> T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.take().unwrap()
                    }
                    #[doc(hidden)]
                    pub unsafe fn from_handle(handle: u32) -> Self {
                        Self {
                            handle: unsafe { _rt::Resource::from_handle(handle) },
                        }
                    }
                    #[doc(hidden)]
                    pub fn take_handle(&self) -> u32 {
                        _rt::Resource::take_handle(&self.handle)
                    }
                    #[doc(hidden)]
                    pub fn handle(&self) -> u32 {
                        _rt::Resource::handle(&self.handle)
                    }
                    #[doc(hidden)]
                    fn type_guard<T: 'static>() {
                        use core::any::TypeId;
                        static mut LAST_TYPE: Option<TypeId> = None;
                        unsafe {
                            assert!(! cfg!(target_feature = "atomics"));
                            let id = TypeId::of::<T>();
                            match LAST_TYPE {
                                Some(ty) => {
                                    assert!(
                                        ty == id, "cannot use two types with this resource type"
                                    )
                                }
                                None => LAST_TYPE = Some(id),
                            }
                        }
                    }
                    #[doc(hidden)]
                    pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
                        Self::type_guard::<T>();
                        let _ = unsafe {
                            _rt::Box::from_raw(handle as *mut _SandboxManagerRep<T>)
                        };
                    }
                    fn as_ptr<T: GuestSandboxManager>(
                        &self,
                    ) -> *mut _SandboxManagerRep<T> {
                        SandboxManager::type_guard::<T>();
                        T::_resource_rep(self.handle()).cast()
                    }
                }
                /// A borrowed version of [`SandboxManager`] which represents a borrowed value
                /// with the lifetime `'a`.
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct SandboxManagerBorrow<'a> {
                    rep: *mut u8,
                    _marker: core::marker::PhantomData<&'a SandboxManager>,
                }
                impl<'a> SandboxManagerBorrow<'a> {
                    #[doc(hidden)]
                    pub unsafe fn lift(rep: usize) -> Self {
                        Self {
                            rep: rep as *mut u8,
                            _marker: core::marker::PhantomData,
                        }
                    }
                    /// Gets access to the underlying `T` in this resource.
                    pub fn get<T: GuestSandboxManager>(&self) -> &T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }
                    fn as_ptr<T: 'static>(&self) -> *mut _SandboxManagerRep<T> {
                        SandboxManager::type_guard::<T>();
                        self.rep.cast()
                    }
                }
                unsafe impl _rt::WasmResource for SandboxManager {
                    #[inline]
                    unsafe fn drop(_handle: u32) {
                        #[cfg(not(target_arch = "wasm32"))]
                        unreachable!();
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]athena:sandbox/sandbox@0.1.0"
                            )]
                            unsafe extern "C" {
                                #[link_name = "[resource-drop]sandbox-manager"]
                                fn drop(_: u32);
                            }
                            unsafe { drop(_handle) };
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_new_cabi<T: Guest>() -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::new();
                    (result0).take_handle() as i32
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_create_instance_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                    arg2: i64,
                    arg3: i64,
                    arg4: i64,
                    arg5: i32,
                    arg6: i32,
                    arg7: *mut u8,
                    arg8: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result4 = T::create_instance(
                        unsafe { SandboxManager::from_handle(arg0 as u32) },
                        match arg1 {
                            0 => None,
                            1 => {
                                let e = {
                                    let base3 = arg7;
                                    let len3 = arg8;
                                    let mut result3 = _rt::Vec::with_capacity(len3);
                                    for i in 0..len3 {
                                        let base = base3
                                            .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                                        let e3 = {
                                            let l0 = *base.add(0).cast::<*mut u8>();
                                            let l1 = *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len2 = l1;
                                            let bytes2 = _rt::Vec::from_raw_parts(
                                                l0.cast(),
                                                len2,
                                                len2,
                                            );
                                            _rt::string_lift(bytes2)
                                        };
                                        result3.push(e3);
                                    }
                                    _rt::cabi_dealloc(
                                        base3,
                                        len3 * (2 * ::core::mem::size_of::<*const u8>()),
                                        ::core::mem::size_of::<*const u8>(),
                                    );
                                    ExecutionPolicy {
                                        max_memory_bytes: arg2 as u64,
                                        max_cpu_time_ms: arg3 as u64,
                                        max_execution_time_ms: arg4 as u64,
                                        allow_network: _rt::bool_lift(arg5 as u8),
                                        allow_file_access: _rt::bool_lift(arg6 as u8),
                                        allowed_syscalls: result3,
                                    }
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                    );
                    let ptr5 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result4 {
                        Ok(e) => {
                            *ptr5.add(0).cast::<u8>() = (0i32) as u8;
                            let vec6 = (e.into_bytes()).into_boxed_slice();
                            let ptr6 = vec6.as_ptr().cast::<u8>();
                            let len6 = vec6.len();
                            ::core::mem::forget(vec6);
                            *ptr5
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len6;
                            *ptr5
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr6.cast_mut();
                        }
                        Err(e) => {
                            *ptr5.add(0).cast::<u8>() = (1i32) as u8;
                            let vec7 = (e.into_bytes()).into_boxed_slice();
                            let ptr7 = vec7.as_ptr().cast::<u8>();
                            let len7 = vec7.len();
                            ::core::mem::forget(vec7);
                            *ptr5
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len7;
                            *ptr5
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr7.cast_mut();
                        }
                    };
                    ptr5
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_create_instance<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                        _ => {
                            let l3 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_execute_cabi<T: Guest>(
                    arg0: i32,
                    arg1: *mut u8,
                    arg2: usize,
                    arg3: *mut u8,
                    arg4: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg2;
                    let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
                    let len1 = arg4;
                    let result2 = T::execute(
                        unsafe { SandboxManager::from_handle(arg0 as u32) },
                        _rt::string_lift(bytes0),
                        _rt::Vec::from_raw_parts(arg3.cast(), len1, len1),
                    );
                    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result2 {
                        Ok(e) => {
                            *ptr3.add(0).cast::<u8>() = (0i32) as u8;
                            let ExecutionResult {
                                stdout: stdout4,
                                stderr: stderr4,
                                exit_code: exit_code4,
                                resource_usage: resource_usage4,
                                security_events: security_events4,
                                execution_time_ms: execution_time_ms4,
                                success: success4,
                            } = e;
                            let vec5 = (stdout4.into_bytes()).into_boxed_slice();
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            ::core::mem::forget(vec5);
                            *ptr3
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *ptr3.add(8).cast::<*mut u8>() = ptr5.cast_mut();
                            let vec6 = (stderr4.into_bytes()).into_boxed_slice();
                            let ptr6 = vec6.as_ptr().cast::<u8>();
                            let len6 = vec6.len();
                            ::core::mem::forget(vec6);
                            *ptr3
                                .add(8 + 3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len6;
                            *ptr3
                                .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr6.cast_mut();
                            *ptr3
                                .add(8 + 4 * ::core::mem::size_of::<*const u8>())
                                .cast::<i32>() = _rt::as_i32(exit_code4);
                            let ResourceUsage {
                                memory_bytes: memory_bytes7,
                                cpu_time_ms: cpu_time_ms7,
                                syscalls_count: syscalls_count7,
                            } = resource_usage4;
                            *ptr3
                                .add(16 + 4 * ::core::mem::size_of::<*const u8>())
                                .cast::<i64>() = _rt::as_i64(memory_bytes7);
                            *ptr3
                                .add(24 + 4 * ::core::mem::size_of::<*const u8>())
                                .cast::<i64>() = _rt::as_i64(cpu_time_ms7);
                            *ptr3
                                .add(32 + 4 * ::core::mem::size_of::<*const u8>())
                                .cast::<i32>() = _rt::as_i32(syscalls_count7);
                            let vec10 = security_events4;
                            let len10 = vec10.len();
                            let layout10 = _rt::alloc::Layout::from_size_align_unchecked(
                                vec10.len() * (8 + 4 * ::core::mem::size_of::<*const u8>()),
                                8,
                            );
                            let result10 = if layout10.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout10).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout10);
                                }
                                ptr
                            } else {
                                ::core::ptr::null_mut()
                            };
                            for (i, e) in vec10.into_iter().enumerate() {
                                let base = result10
                                    .add(i * (8 + 4 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let SecurityEvent {
                                        timestamp: timestamp8,
                                        event_type: event_type8,
                                        description: description8,
                                        severity: severity8,
                                    } = e;
                                    *base.add(0).cast::<i64>() = _rt::as_i64(timestamp8);
                                    *base.add(8).cast::<u8>() = (event_type8.clone() as i32)
                                        as u8;
                                    let vec9 = (description8.into_bytes()).into_boxed_slice();
                                    let ptr9 = vec9.as_ptr().cast::<u8>();
                                    let len9 = vec9.len();
                                    ::core::mem::forget(vec9);
                                    *base
                                        .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len9;
                                    *base
                                        .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr9.cast_mut();
                                    *base
                                        .add(8 + 3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (severity8.clone() as i32) as u8;
                                }
                            }
                            *ptr3
                                .add(40 + 5 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len10;
                            *ptr3
                                .add(40 + 4 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = result10;
                            *ptr3
                                .add(40 + 6 * ::core::mem::size_of::<*const u8>())
                                .cast::<i64>() = _rt::as_i64(execution_time_ms4);
                            *ptr3
                                .add(48 + 6 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (match success4 {
                                true => 1,
                                false => 0,
                            }) as u8;
                        }
                        Err(e) => {
                            *ptr3.add(0).cast::<u8>() = (1i32) as u8;
                            let vec11 = (e.into_bytes()).into_boxed_slice();
                            let ptr11 = vec11.as_ptr().cast::<u8>();
                            let len11 = vec11.len();
                            ::core::mem::forget(vec11);
                            *ptr3
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len11;
                            *ptr3.add(8).cast::<*mut u8>() = ptr11.cast_mut();
                        }
                    };
                    ptr3
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_execute<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0.add(8).cast::<*mut u8>();
                            let l2 = *arg0
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                            let l3 = *arg0
                                .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(8 + 3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                            let l5 = *arg0
                                .add(40 + 4 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l6 = *arg0
                                .add(40 + 5 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base9 = l5;
                            let len9 = l6;
                            for i in 0..len9 {
                                let base = base9
                                    .add(i * (8 + 4 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let l7 = *base
                                        .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l8 = *base
                                        .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l7, l8, 1);
                                }
                            }
                            _rt::cabi_dealloc(
                                base9,
                                len9 * (8 + 4 * ::core::mem::size_of::<*const u8>()),
                                8,
                            );
                        }
                        _ => {
                            let l10 = *arg0.add(8).cast::<*mut u8>();
                            let l11 = *arg0
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l10, l11, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_terminate_instance_cabi<T: Guest>(
                    arg0: i32,
                    arg1: *mut u8,
                    arg2: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg2;
                    let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
                    let result1 = T::terminate_instance(
                        unsafe { SandboxManager::from_handle(arg0 as u32) },
                        _rt::string_lift(bytes0),
                    );
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result1 {
                        Ok(_) => {
                            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                        }
                        Err(e) => {
                            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                            let vec3 = (e.into_bytes()).into_boxed_slice();
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            ::core::mem::forget(vec3);
                            *ptr2
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *ptr2
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr3.cast_mut();
                        }
                    };
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_terminate_instance<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_get_instance_stats_cabi<T: Guest>(
                    arg0: i32,
                    arg1: *mut u8,
                    arg2: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg2;
                    let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
                    let result1 = T::get_instance_stats(
                        unsafe { SandboxManager::from_handle(arg0 as u32) },
                        _rt::string_lift(bytes0),
                    );
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result1 {
                        Ok(e) => {
                            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                            let ResourceUsage {
                                memory_bytes: memory_bytes3,
                                cpu_time_ms: cpu_time_ms3,
                                syscalls_count: syscalls_count3,
                            } = e;
                            *ptr2.add(8).cast::<i64>() = _rt::as_i64(memory_bytes3);
                            *ptr2.add(16).cast::<i64>() = _rt::as_i64(cpu_time_ms3);
                            *ptr2.add(24).cast::<i32>() = _rt::as_i32(syscalls_count3);
                        }
                        Err(e) => {
                            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                            let vec4 = (e.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr2
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr2.add(8).cast::<*mut u8>() = ptr4.cast_mut();
                        }
                    };
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_get_instance_stats<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0.add(8).cast::<*mut u8>();
                            let l2 = *arg0
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_constructor_sandbox_manager_cabi<
                    T: GuestSandboxManager,
                >() -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = SandboxManager::new(T::new());
                    (result0).take_handle() as i32
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_sandbox_manager_create_instance_cabi<
                    T: GuestSandboxManager,
                >(
                    arg0: *mut u8,
                    arg1: i32,
                    arg2: i64,
                    arg3: i64,
                    arg4: i64,
                    arg5: i32,
                    arg6: i32,
                    arg7: *mut u8,
                    arg8: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result4 = T::create_instance(
                        unsafe { SandboxManagerBorrow::lift(arg0 as u32 as usize) }
                            .get(),
                        match arg1 {
                            0 => None,
                            1 => {
                                let e = {
                                    let base3 = arg7;
                                    let len3 = arg8;
                                    let mut result3 = _rt::Vec::with_capacity(len3);
                                    for i in 0..len3 {
                                        let base = base3
                                            .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                                        let e3 = {
                                            let l0 = *base.add(0).cast::<*mut u8>();
                                            let l1 = *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len2 = l1;
                                            let bytes2 = _rt::Vec::from_raw_parts(
                                                l0.cast(),
                                                len2,
                                                len2,
                                            );
                                            _rt::string_lift(bytes2)
                                        };
                                        result3.push(e3);
                                    }
                                    _rt::cabi_dealloc(
                                        base3,
                                        len3 * (2 * ::core::mem::size_of::<*const u8>()),
                                        ::core::mem::size_of::<*const u8>(),
                                    );
                                    ExecutionPolicy {
                                        max_memory_bytes: arg2 as u64,
                                        max_cpu_time_ms: arg3 as u64,
                                        max_execution_time_ms: arg4 as u64,
                                        allow_network: _rt::bool_lift(arg5 as u8),
                                        allow_file_access: _rt::bool_lift(arg6 as u8),
                                        allowed_syscalls: result3,
                                    }
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                    );
                    let ptr5 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result4 {
                        Ok(e) => {
                            *ptr5.add(0).cast::<u8>() = (0i32) as u8;
                            let vec6 = (e.into_bytes()).into_boxed_slice();
                            let ptr6 = vec6.as_ptr().cast::<u8>();
                            let len6 = vec6.len();
                            ::core::mem::forget(vec6);
                            *ptr5
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len6;
                            *ptr5
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr6.cast_mut();
                        }
                        Err(e) => {
                            *ptr5.add(0).cast::<u8>() = (1i32) as u8;
                            let vec7 = (e.into_bytes()).into_boxed_slice();
                            let ptr7 = vec7.as_ptr().cast::<u8>();
                            let len7 = vec7.len();
                            ::core::mem::forget(vec7);
                            *ptr5
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len7;
                            *ptr5
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr7.cast_mut();
                        }
                    };
                    ptr5
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_method_sandbox_manager_create_instance<
                    T: GuestSandboxManager,
                >(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                        _ => {
                            let l3 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_sandbox_manager_execute_cabi<
                    T: GuestSandboxManager,
                >(
                    arg0: *mut u8,
                    arg1: *mut u8,
                    arg2: usize,
                    arg3: *mut u8,
                    arg4: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg2;
                    let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
                    let len1 = arg4;
                    let result2 = T::execute(
                        unsafe { SandboxManagerBorrow::lift(arg0 as u32 as usize) }
                            .get(),
                        _rt::string_lift(bytes0),
                        _rt::Vec::from_raw_parts(arg3.cast(), len1, len1),
                    );
                    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result2 {
                        Ok(e) => {
                            *ptr3.add(0).cast::<u8>() = (0i32) as u8;
                            let ExecutionResult {
                                stdout: stdout4,
                                stderr: stderr4,
                                exit_code: exit_code4,
                                resource_usage: resource_usage4,
                                security_events: security_events4,
                                execution_time_ms: execution_time_ms4,
                                success: success4,
                            } = e;
                            let vec5 = (stdout4.into_bytes()).into_boxed_slice();
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            ::core::mem::forget(vec5);
                            *ptr3
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *ptr3.add(8).cast::<*mut u8>() = ptr5.cast_mut();
                            let vec6 = (stderr4.into_bytes()).into_boxed_slice();
                            let ptr6 = vec6.as_ptr().cast::<u8>();
                            let len6 = vec6.len();
                            ::core::mem::forget(vec6);
                            *ptr3
                                .add(8 + 3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len6;
                            *ptr3
                                .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr6.cast_mut();
                            *ptr3
                                .add(8 + 4 * ::core::mem::size_of::<*const u8>())
                                .cast::<i32>() = _rt::as_i32(exit_code4);
                            let ResourceUsage {
                                memory_bytes: memory_bytes7,
                                cpu_time_ms: cpu_time_ms7,
                                syscalls_count: syscalls_count7,
                            } = resource_usage4;
                            *ptr3
                                .add(16 + 4 * ::core::mem::size_of::<*const u8>())
                                .cast::<i64>() = _rt::as_i64(memory_bytes7);
                            *ptr3
                                .add(24 + 4 * ::core::mem::size_of::<*const u8>())
                                .cast::<i64>() = _rt::as_i64(cpu_time_ms7);
                            *ptr3
                                .add(32 + 4 * ::core::mem::size_of::<*const u8>())
                                .cast::<i32>() = _rt::as_i32(syscalls_count7);
                            let vec10 = security_events4;
                            let len10 = vec10.len();
                            let layout10 = _rt::alloc::Layout::from_size_align_unchecked(
                                vec10.len() * (8 + 4 * ::core::mem::size_of::<*const u8>()),
                                8,
                            );
                            let result10 = if layout10.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout10).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout10);
                                }
                                ptr
                            } else {
                                ::core::ptr::null_mut()
                            };
                            for (i, e) in vec10.into_iter().enumerate() {
                                let base = result10
                                    .add(i * (8 + 4 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let SecurityEvent {
                                        timestamp: timestamp8,
                                        event_type: event_type8,
                                        description: description8,
                                        severity: severity8,
                                    } = e;
                                    *base.add(0).cast::<i64>() = _rt::as_i64(timestamp8);
                                    *base.add(8).cast::<u8>() = (event_type8.clone() as i32)
                                        as u8;
                                    let vec9 = (description8.into_bytes()).into_boxed_slice();
                                    let ptr9 = vec9.as_ptr().cast::<u8>();
                                    let len9 = vec9.len();
                                    ::core::mem::forget(vec9);
                                    *base
                                        .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len9;
                                    *base
                                        .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr9.cast_mut();
                                    *base
                                        .add(8 + 3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (severity8.clone() as i32) as u8;
                                }
                            }
                            *ptr3
                                .add(40 + 5 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len10;
                            *ptr3
                                .add(40 + 4 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = result10;
                            *ptr3
                                .add(40 + 6 * ::core::mem::size_of::<*const u8>())
                                .cast::<i64>() = _rt::as_i64(execution_time_ms4);
                            *ptr3
                                .add(48 + 6 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (match success4 {
                                true => 1,
                                false => 0,
                            }) as u8;
                        }
                        Err(e) => {
                            *ptr3.add(0).cast::<u8>() = (1i32) as u8;
                            let vec11 = (e.into_bytes()).into_boxed_slice();
                            let ptr11 = vec11.as_ptr().cast::<u8>();
                            let len11 = vec11.len();
                            ::core::mem::forget(vec11);
                            *ptr3
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len11;
                            *ptr3.add(8).cast::<*mut u8>() = ptr11.cast_mut();
                        }
                    };
                    ptr3
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_method_sandbox_manager_execute<
                    T: GuestSandboxManager,
                >(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0.add(8).cast::<*mut u8>();
                            let l2 = *arg0
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                            let l3 = *arg0
                                .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(8 + 3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                            let l5 = *arg0
                                .add(40 + 4 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l6 = *arg0
                                .add(40 + 5 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base9 = l5;
                            let len9 = l6;
                            for i in 0..len9 {
                                let base = base9
                                    .add(i * (8 + 4 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let l7 = *base
                                        .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l8 = *base
                                        .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l7, l8, 1);
                                }
                            }
                            _rt::cabi_dealloc(
                                base9,
                                len9 * (8 + 4 * ::core::mem::size_of::<*const u8>()),
                                8,
                            );
                        }
                        _ => {
                            let l10 = *arg0.add(8).cast::<*mut u8>();
                            let l11 = *arg0
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l10, l11, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_sandbox_manager_terminate_instance_cabi<
                    T: GuestSandboxManager,
                >(arg0: *mut u8, arg1: *mut u8, arg2: usize) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg2;
                    let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
                    let result1 = T::terminate_instance(
                        unsafe { SandboxManagerBorrow::lift(arg0 as u32 as usize) }
                            .get(),
                        _rt::string_lift(bytes0),
                    );
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result1 {
                        Ok(_) => {
                            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                        }
                        Err(e) => {
                            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                            let vec3 = (e.into_bytes()).into_boxed_slice();
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            ::core::mem::forget(vec3);
                            *ptr2
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *ptr2
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr3.cast_mut();
                        }
                    };
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_method_sandbox_manager_terminate_instance<
                    T: GuestSandboxManager,
                >(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_sandbox_manager_get_instance_stats_cabi<
                    T: GuestSandboxManager,
                >(arg0: *mut u8, arg1: *mut u8, arg2: usize) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg2;
                    let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
                    let result1 = T::get_instance_stats(
                        unsafe { SandboxManagerBorrow::lift(arg0 as u32 as usize) }
                            .get(),
                        _rt::string_lift(bytes0),
                    );
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result1 {
                        Ok(e) => {
                            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                            let ResourceUsage {
                                memory_bytes: memory_bytes3,
                                cpu_time_ms: cpu_time_ms3,
                                syscalls_count: syscalls_count3,
                            } = e;
                            *ptr2.add(8).cast::<i64>() = _rt::as_i64(memory_bytes3);
                            *ptr2.add(16).cast::<i64>() = _rt::as_i64(cpu_time_ms3);
                            *ptr2.add(24).cast::<i32>() = _rt::as_i32(syscalls_count3);
                        }
                        Err(e) => {
                            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                            let vec4 = (e.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr2
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr2.add(8).cast::<*mut u8>() = ptr4.cast_mut();
                        }
                    };
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_method_sandbox_manager_get_instance_stats<
                    T: GuestSandboxManager,
                >(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0.add(8).cast::<*mut u8>();
                            let l2 = *arg0
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_sandbox_manager_list_instances_cabi<
                    T: GuestSandboxManager,
                >(arg0: *mut u8) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::list_instances(
                        unsafe { SandboxManagerBorrow::lift(arg0 as u32 as usize) }.get(),
                    );
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec3 = result0;
                    let len3 = vec3.len();
                    let layout3 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec3.len() * (2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result3 = if layout3.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout3).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout3);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec3.into_iter().enumerate() {
                        let base = result3
                            .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                        {
                            let vec2 = (e.into_bytes()).into_boxed_slice();
                            let ptr2 = vec2.as_ptr().cast::<u8>();
                            let len2 = vec2.len();
                            ::core::mem::forget(vec2);
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len2;
                            *base.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                        }
                    }
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
                    *ptr1.add(0).cast::<*mut u8>() = result3;
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_method_sandbox_manager_list_instances<
                    T: GuestSandboxManager,
                >(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base4 = l0;
                    let len4 = l1;
                    for i in 0..len4 {
                        let base = base4
                            .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                        {
                            let l2 = *base.add(0).cast::<*mut u8>();
                            let l3 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l2, l3, 1);
                        }
                    }
                    _rt::cabi_dealloc(
                        base4,
                        len4 * (2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                }
                pub trait Guest {
                    type SandboxManager: GuestSandboxManager;
                    /// Create sandbox manager
                    fn new() -> SandboxManager;
                    /// Create sandbox instance
                    fn create_instance(
                        handle: SandboxManager,
                        policy: Option<ExecutionPolicy>,
                    ) -> Result<_rt::String, _rt::String>;
                    /// Execute code in instance
                    fn execute(
                        handle: SandboxManager,
                        instance_id: _rt::String,
                        code: _rt::Vec<u8>,
                    ) -> Result<ExecutionResult, _rt::String>;
                    /// Terminate instance
                    fn terminate_instance(
                        handle: SandboxManager,
                        instance_id: _rt::String,
                    ) -> Result<(), _rt::String>;
                    /// Get instance stats
                    fn get_instance_stats(
                        handle: SandboxManager,
                        instance_id: _rt::String,
                    ) -> Result<ResourceUsage, _rt::String>;
                }
                pub trait GuestSandboxManager: 'static {
                    #[doc(hidden)]
                    unsafe fn _resource_new(val: *mut u8) -> u32
                    where
                        Self: Sized,
                    {
                        #[cfg(not(target_arch = "wasm32"))]
                        {
                            let _ = val;
                            unreachable!();
                        }
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]athena:sandbox/sandbox@0.1.0"
                            )]
                            unsafe extern "C" {
                                #[link_name = "[resource-new]sandbox-manager"]
                                fn new(_: *mut u8) -> u32;
                            }
                            unsafe { new(val) }
                        }
                    }
                    #[doc(hidden)]
                    fn _resource_rep(handle: u32) -> *mut u8
                    where
                        Self: Sized,
                    {
                        #[cfg(not(target_arch = "wasm32"))]
                        {
                            let _ = handle;
                            unreachable!();
                        }
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]athena:sandbox/sandbox@0.1.0"
                            )]
                            unsafe extern "C" {
                                #[link_name = "[resource-rep]sandbox-manager"]
                                fn rep(_: u32) -> *mut u8;
                            }
                            unsafe { rep(handle) }
                        }
                    }
                    fn new() -> Self;
                    fn create_instance(
                        &self,
                        policy: Option<ExecutionPolicy>,
                    ) -> Result<_rt::String, _rt::String>;
                    fn execute(
                        &self,
                        instance_id: _rt::String,
                        code: _rt::Vec<u8>,
                    ) -> Result<ExecutionResult, _rt::String>;
                    fn terminate_instance(
                        &self,
                        instance_id: _rt::String,
                    ) -> Result<(), _rt::String>;
                    fn get_instance_stats(
                        &self,
                        instance_id: _rt::String,
                    ) -> Result<ResourceUsage, _rt::String>;
                    fn list_instances(&self) -> _rt::Vec<_rt::String>;
                }
                #[doc(hidden)]
                macro_rules! __export_athena_sandbox_sandbox_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "athena:sandbox/sandbox@0.1.0#new")] unsafe extern "C" fn
                        export_new() -> i32 { unsafe { $($path_to_types)*::
                        _export_new_cabi::<$ty > () } } #[unsafe (export_name =
                        "athena:sandbox/sandbox@0.1.0#create-instance")] unsafe extern
                        "C" fn export_create_instance(arg0 : i32, arg1 : i32, arg2 : i64,
                        arg3 : i64, arg4 : i64, arg5 : i32, arg6 : i32, arg7 : * mut u8,
                        arg8 : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_create_instance_cabi::<$ty > (arg0, arg1, arg2, arg3,
                        arg4, arg5, arg6, arg7, arg8) } } #[unsafe (export_name =
                        "cabi_post_athena:sandbox/sandbox@0.1.0#create-instance")] unsafe
                        extern "C" fn _post_return_create_instance(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*:: __post_return_create_instance::<$ty
                        > (arg0) } } #[unsafe (export_name =
                        "athena:sandbox/sandbox@0.1.0#execute")] unsafe extern "C" fn
                        export_execute(arg0 : i32, arg1 : * mut u8, arg2 : usize, arg3 :
                        * mut u8, arg4 : usize,) -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_execute_cabi::<$ty > (arg0, arg1,
                        arg2, arg3, arg4) } } #[unsafe (export_name =
                        "cabi_post_athena:sandbox/sandbox@0.1.0#execute")] unsafe extern
                        "C" fn _post_return_execute(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_execute::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "athena:sandbox/sandbox@0.1.0#terminate-instance")] unsafe extern
                        "C" fn export_terminate_instance(arg0 : i32, arg1 : * mut u8,
                        arg2 : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_terminate_instance_cabi::<$ty > (arg0, arg1, arg2) } }
                        #[unsafe (export_name =
                        "cabi_post_athena:sandbox/sandbox@0.1.0#terminate-instance")]
                        unsafe extern "C" fn _post_return_terminate_instance(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_terminate_instance::<$ty > (arg0) } } #[unsafe
                        (export_name =
                        "athena:sandbox/sandbox@0.1.0#get-instance-stats")] unsafe extern
                        "C" fn export_get_instance_stats(arg0 : i32, arg1 : * mut u8,
                        arg2 : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_get_instance_stats_cabi::<$ty > (arg0, arg1, arg2) } }
                        #[unsafe (export_name =
                        "cabi_post_athena:sandbox/sandbox@0.1.0#get-instance-stats")]
                        unsafe extern "C" fn _post_return_get_instance_stats(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_get_instance_stats::<$ty > (arg0) } } #[unsafe
                        (export_name =
                        "athena:sandbox/sandbox@0.1.0#[constructor]sandbox-manager")]
                        unsafe extern "C" fn export_constructor_sandbox_manager() -> i32
                        { unsafe { $($path_to_types)*::
                        _export_constructor_sandbox_manager_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::SandboxManager > () } } #[unsafe
                        (export_name =
                        "athena:sandbox/sandbox@0.1.0#[method]sandbox-manager.create-instance")]
                        unsafe extern "C" fn
                        export_method_sandbox_manager_create_instance(arg0 : * mut u8,
                        arg1 : i32, arg2 : i64, arg3 : i64, arg4 : i64, arg5 : i32, arg6
                        : i32, arg7 : * mut u8, arg8 : usize,) -> * mut u8 { unsafe {
                        $($path_to_types)*::
                        _export_method_sandbox_manager_create_instance_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::SandboxManager > (arg0, arg1, arg2,
                        arg3, arg4, arg5, arg6, arg7, arg8) } } #[unsafe (export_name =
                        "cabi_post_athena:sandbox/sandbox@0.1.0#[method]sandbox-manager.create-instance")]
                        unsafe extern "C" fn
                        _post_return_method_sandbox_manager_create_instance(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_method_sandbox_manager_create_instance::<<$ty as
                        $($path_to_types)*:: Guest >::SandboxManager > (arg0) } }
                        #[unsafe (export_name =
                        "athena:sandbox/sandbox@0.1.0#[method]sandbox-manager.execute")]
                        unsafe extern "C" fn export_method_sandbox_manager_execute(arg0 :
                        * mut u8, arg1 : * mut u8, arg2 : usize, arg3 : * mut u8, arg4 :
                        usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_method_sandbox_manager_execute_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::SandboxManager > (arg0, arg1, arg2,
                        arg3, arg4) } } #[unsafe (export_name =
                        "cabi_post_athena:sandbox/sandbox@0.1.0#[method]sandbox-manager.execute")]
                        unsafe extern "C" fn
                        _post_return_method_sandbox_manager_execute(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*::
                        __post_return_method_sandbox_manager_execute::<<$ty as
                        $($path_to_types)*:: Guest >::SandboxManager > (arg0) } }
                        #[unsafe (export_name =
                        "athena:sandbox/sandbox@0.1.0#[method]sandbox-manager.terminate-instance")]
                        unsafe extern "C" fn
                        export_method_sandbox_manager_terminate_instance(arg0 : * mut u8,
                        arg1 : * mut u8, arg2 : usize,) -> * mut u8 { unsafe {
                        $($path_to_types)*::
                        _export_method_sandbox_manager_terminate_instance_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::SandboxManager > (arg0, arg1, arg2)
                        } } #[unsafe (export_name =
                        "cabi_post_athena:sandbox/sandbox@0.1.0#[method]sandbox-manager.terminate-instance")]
                        unsafe extern "C" fn
                        _post_return_method_sandbox_manager_terminate_instance(arg0 : *
                        mut u8,) { unsafe { $($path_to_types)*::
                        __post_return_method_sandbox_manager_terminate_instance::<<$ty as
                        $($path_to_types)*:: Guest >::SandboxManager > (arg0) } }
                        #[unsafe (export_name =
                        "athena:sandbox/sandbox@0.1.0#[method]sandbox-manager.get-instance-stats")]
                        unsafe extern "C" fn
                        export_method_sandbox_manager_get_instance_stats(arg0 : * mut u8,
                        arg1 : * mut u8, arg2 : usize,) -> * mut u8 { unsafe {
                        $($path_to_types)*::
                        _export_method_sandbox_manager_get_instance_stats_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::SandboxManager > (arg0, arg1, arg2)
                        } } #[unsafe (export_name =
                        "cabi_post_athena:sandbox/sandbox@0.1.0#[method]sandbox-manager.get-instance-stats")]
                        unsafe extern "C" fn
                        _post_return_method_sandbox_manager_get_instance_stats(arg0 : *
                        mut u8,) { unsafe { $($path_to_types)*::
                        __post_return_method_sandbox_manager_get_instance_stats::<<$ty as
                        $($path_to_types)*:: Guest >::SandboxManager > (arg0) } }
                        #[unsafe (export_name =
                        "athena:sandbox/sandbox@0.1.0#[method]sandbox-manager.list-instances")]
                        unsafe extern "C" fn
                        export_method_sandbox_manager_list_instances(arg0 : * mut u8,) ->
                        * mut u8 { unsafe { $($path_to_types)*::
                        _export_method_sandbox_manager_list_instances_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::SandboxManager > (arg0) } }
                        #[unsafe (export_name =
                        "cabi_post_athena:sandbox/sandbox@0.1.0#[method]sandbox-manager.list-instances")]
                        unsafe extern "C" fn
                        _post_return_method_sandbox_manager_list_instances(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_method_sandbox_manager_list_instances::<<$ty as
                        $($path_to_types)*:: Guest >::SandboxManager > (arg0) } } const _
                        : () = { #[doc(hidden)] #[unsafe (export_name =
                        "athena:sandbox/sandbox@0.1.0#[dtor]sandbox-manager")]
                        #[allow(non_snake_case)] unsafe extern "C" fn dtor(rep : * mut
                        u8) { unsafe { $($path_to_types)*:: SandboxManager::dtor::< <$ty
                        as $($path_to_types)*:: Guest >::SandboxManager > (rep) } } }; };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_athena_sandbox_sandbox_0_1_0_cabi;
                #[repr(align(8))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 56 + 6 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 56
                        + 6 * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    use core::fmt;
    use core::marker;
    use core::sync::atomic::{AtomicU32, Ordering::Relaxed};
    /// A type which represents a component model resource, either imported or
    /// exported into this component.
    ///
    /// This is a low-level wrapper which handles the lifetime of the resource
    /// (namely this has a destructor). The `T` provided defines the component model
    /// intrinsics that this wrapper uses.
    ///
    /// One of the chief purposes of this type is to provide `Deref` implementations
    /// to access the underlying data when it is owned.
    ///
    /// This type is primarily used in generated code for exported and imported
    /// resources.
    #[repr(transparent)]
    pub struct Resource<T: WasmResource> {
        handle: AtomicU32,
        _marker: marker::PhantomData<T>,
    }
    /// A trait which all wasm resources implement, namely providing the ability to
    /// drop a resource.
    ///
    /// This generally is implemented by generated code, not user-facing code.
    #[allow(clippy::missing_safety_doc)]
    pub unsafe trait WasmResource {
        /// Invokes the `[resource-drop]...` intrinsic.
        unsafe fn drop(handle: u32);
    }
    impl<T: WasmResource> Resource<T> {
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
            debug_assert!(handle != u32::MAX);
            Self {
                handle: AtomicU32::new(handle),
                _marker: marker::PhantomData,
            }
        }
        /// Takes ownership of the handle owned by `resource`.
        ///
        /// Note that this ideally would be `into_handle` taking `Resource<T>` by
        /// ownership. The code generator does not enable that in all situations,
        /// unfortunately, so this is provided instead.
        ///
        /// Also note that `take_handle` is in theory only ever called on values
        /// owned by a generated function. For example a generated function might
        /// take `Resource<T>` as an argument but then call `take_handle` on a
        /// reference to that argument. In that sense the dynamic nature of
        /// `take_handle` should only be exposed internally to generated code, not
        /// to user code.
        #[doc(hidden)]
        pub fn take_handle(resource: &Resource<T>) -> u32 {
            resource.handle.swap(u32::MAX, Relaxed)
        }
        #[doc(hidden)]
        pub fn handle(resource: &Resource<T>) -> u32 {
            resource.handle.load(Relaxed)
        }
    }
    impl<T: WasmResource> fmt::Debug for Resource<T> {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            f.debug_struct("Resource").field("handle", &self.handle).finish()
        }
    }
    impl<T: WasmResource> Drop for Resource<T> {
        fn drop(&mut self) {
            unsafe {
                match self.handle.load(Relaxed) {
                    u32::MAX => {}
                    other => T::drop(other),
                }
            }
        }
    }
    pub use alloc_crate::boxed::Box;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    // SAFETY NOTE: Modified from generated code to prevent panics on invalid UTF-8.
    // For malware analysis, we must handle potentially malicious/corrupted data gracefully.
    // Original wit-bindgen code used .unwrap() in debug and unchecked in release.
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        String::from_utf8(bytes).unwrap_or_else(|e| {
            String::from_utf8_lossy(&e.into_bytes()).into_owned()
        })
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    pub use alloc_crate::alloc;
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_sandbox_component_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::athena::sandbox::sandbox::__export_athena_sandbox_sandbox_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::athena::sandbox::sandbox);
    };
}
#[doc(inline)]
pub(crate) use __export_sandbox_component_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:athena:sandbox@0.1.0:sandbox-component:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1490] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xca\x0a\x01A\x02\x01\
A\x02\x01B.\x01r\x03\x0cmemory-bytesw\x0bcpu-time-msw\x0esyscalls-county\x04\0\x0e\
resource-usage\x03\0\0\x01m\x06\x0fsyscall-blocked\x14memory-limit-reached\x11cp\
u-limit-reached\x16network-access-attempt\x13file-access-attempt\x13suspicious-b\
ehavior\x04\0\x13security-event-type\x03\0\x02\x01m\x04\x03low\x06medium\x04high\
\x08critical\x04\0\x11security-severity\x03\0\x04\x01r\x04\x09timestampw\x0aeven\
t-type\x03\x0bdescriptions\x08severity\x05\x04\0\x0esecurity-event\x03\0\x06\x01\
ps\x01r\x06\x10max-memory-bytesw\x0fmax-cpu-time-msw\x15max-execution-time-msw\x0d\
allow-network\x7f\x11allow-file-access\x7f\x10allowed-syscalls\x08\x04\0\x10exec\
ution-policy\x03\0\x09\x01p\x07\x01r\x07\x06stdouts\x06stderrs\x09exit-codez\x0e\
resource-usage\x01\x0fsecurity-events\x0b\x11execution-time-msw\x07success\x7f\x04\
\0\x10execution-result\x03\0\x0c\x01p}\x01r\x04\x0binstance-ids\x09timestampw\x0c\
memory-state\x0e\x08metadatas\x04\0\x11instance-snapshot\x03\0\x0f\x04\0\x0fsand\
box-manager\x03\x01\x01i\x11\x01@\0\0\x12\x04\0\x1c[constructor]sandbox-manager\x01\
\x13\x01h\x11\x01k\x0a\x01j\x01s\x01s\x01@\x02\x04self\x14\x06policy\x15\0\x16\x04\
\0'[method]sandbox-manager.create-instance\x01\x17\x01j\x01\x0d\x01s\x01@\x03\x04\
self\x14\x0binstance-ids\x04code\x0e\0\x18\x04\0\x1f[method]sandbox-manager.exec\
ute\x01\x19\x01j\0\x01s\x01@\x02\x04self\x14\x0binstance-ids\0\x1a\x04\0*[method\
]sandbox-manager.terminate-instance\x01\x1b\x01j\x01\x01\x01s\x01@\x02\x04self\x14\
\x0binstance-ids\0\x1c\x04\0*[method]sandbox-manager.get-instance-stats\x01\x1d\x01\
@\x01\x04self\x14\0\x08\x04\0&[method]sandbox-manager.list-instances\x01\x1e\x04\
\0\x03new\x01\x13\x01@\x02\x06handle\x12\x06policy\x15\0\x16\x04\0\x0fcreate-ins\
tance\x01\x1f\x01@\x03\x06handle\x12\x0binstance-ids\x04code\x0e\0\x18\x04\0\x07\
execute\x01\x20\x01@\x02\x06handle\x12\x0binstance-ids\0\x1a\x04\0\x12terminate-\
instance\x01!\x01@\x02\x06handle\x12\x0binstance-ids\0\x1c\x04\0\x12get-instance\
-stats\x01\"\x04\0\x1cathena:sandbox/sandbox@0.1.0\x05\0\x04\0&athena:sandbox/sa\
ndbox-component@0.1.0\x04\0\x0b\x17\x01\0\x11sandbox-component\x03\0\0\0G\x09pro\
ducers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x06\
0.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
