apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: athena

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - redis.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/name: athena
  app.kubernetes.io/instance: production
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: athena-platform

images:
  - name: athena
    newTag: latest