apiVersion: v1
kind: Service
metadata:
  name: athena-service
  labels:
    app: athena
    component: api
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: metrics
    protocol: TCP
  selector:
    app: athena
    component: api
---
apiVersion: v1
kind: Service
metadata:
  name: athena-nodeport
  labels:
    app: athena
    component: api
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
    nodePort: 30080
  selector:
    app: athena
    component: api