name: Build Tauri App

on:
  push:
    branches: [ main, tauri-migration ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.platform }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install Linux dependencies
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
    
    - name: Install dependencies
      working-directory: ./athena-v2
      run: npm install
    
    - name: Build frontend
      working-directory: ./athena-v2
      run: npm run build
    
    - name: Build Tauri app
      working-directory: ./athena-v2
      run: npm run tauri build
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tauri-app-${{ matrix.platform }}
        path: |
          athena-v2/src-tauri/target/release/bundle/